---
roles:
  - name: db-pull
    src: https://github.com/le-phare/ansible-db-pull
    version: v1.5.0

  - name: cbrunnkvist.ansistrano-symfony-deploy
    src: https://github.com/le-phare/ansistrano-symfony-deploy

collections:
  - name: bitwarden.secrets
