- name: LEPHARE | COMPOSER | Dump {{ symfony_env }} environment
  shell: chdir={{ansistrano_release_path.stdout}}
    export APP_ENV={{symfony_env}} && {{symfony_php_path}} {{symfony_composer_path}} dump-env {{symfony_env}}
