- name: Add lephare_composer_home directory to current user $PATH.
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: 'export COMPOSER_HOME={{ lephare_composer_home }}'
    create: true
    backup: true

- name: LEPHARE | COMPOSER | Setup private registry
  template:
    src: composer/auth.json.j2
    dest: "{{ lephare_composer_home }}/auth.json"
    mode: 0600
  when: lephare_packagist_com_token != "" or lephare_gitlab_token != ""
