---
roles:
  - name: db-pull
    src: https://github.com/le-phare/ansible-db-pull
    version: v1.5.0

  - name: lephare.ansible-deploy
    src: https://github.com/le-phare/ansible-deploy

  - name: cbrunnkvist.ansistrano-symfony-deploy
    src: https://github.com/le-phare/ansistrano-symfony-deploy

collections:
  - name: community.general
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com

  - name: community.mysql
    source: https://galaxy.ansible.com

  - name: community.postgresql
    source: https://galaxy.ansible.com
