- include_tasks: "../../lephare.ansible-deploy/config/steps/cachetool.yml"
  when: lephare_cachetool_enable

- include_tasks: "../../lephare.ansible-deploy/config/steps/install_crontab.yml"
  when: lephare_crontab_install

- include_tasks: "../../lephare.ansible-deploy/config/steps/remove_crontab.yml"
  when: not lephare_crontab_install

- include_tasks: "../../lephare.ansible-deploy/config/steps/symfony/messenger/after_symlink.yml"
  when: symfony_messenger_enable

- include_tasks: "../../lephare.ansible-deploy/config/steps/invalidate_cloudfront.yml"
  when: lephare_cloudfront_invalidate

- include_tasks: "../../lephare.ansible-deploy/config/steps/rollbar_notify.yml"
  when: lephare_rollbar_notify

- include_tasks: "../../lephare.ansible-deploy/config/steps/sentry_notify.yml"
  when: lephare_sentry_notify

- include_tasks: "../../lephare.ansible-deploy/config/steps/tideways.yml"
  when: lephare_tideways_notify

- include_tasks: "../../lephare.ansible-deploy/config/steps/slack_notify.yml"
  when: lephare_slack_notify
