- include_tasks: "../../lephare.ansible-deploy/config/steps/composer/private_registry.yml"
  when: lephare_packagist_com_token is defined

- name: Dump an existing database to a file (with compression)
  when: lephare_dump_database
  community.postgresql.postgresql_db:
    name: "{{ app_database_name }}"
    login_host: "{{ app_database_login_host | default(omit) }}"
    login_port: "{{ app_database_login_port | int | default(omit) }}"
    login_user: "{{ app_database_user }}"
    login_password: "{{ app_database_password }}"
    state: dump
    target: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}/{{ db_pull_remote_database_name }}.sql.gz"

- name: Setup {{ symfony_env }} secrets decrypt key
  template:
    src: symfony/secrets_private.php.j2
    dest: "{{ ansistrano_release_path.stdout }}/config/secrets/{{ symfony_env }}/{{ symfony_env }}.decrypt.private.php"
    mode: 0644
  when: symfony_secret_private_key is defined
