- name: LEPHARE - install latest Adminer
  get_url:
    url: https://www.adminer.org/latest.php
    dest: "{{ lephare_install_adminer_path }}/{{lephare_install_adminer_filename}}"
  ignore_errors: True
