- name: LEPHARE - PHP Version
  shell: "{{ symfony_php_path | default('php', true) }} -v | awk '/^PHP / { print $2 }'"
  register: php_version

- name: LEPHARE - PHP - Extensions
  shell: "{{ symfony_php_path | default('php', true) }} -m | awk '/^[A-Za-z]+$/ { print tolower($1) }'"
  register: php_extensions

- name: LEPHARE - Set facts
  set_fact:
    php_facts:
      version: "{{ php_version.stdout }}"
      extensions: "{{ php_extensions.stdout_lines }}"
